#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DangKyLichHen.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DangKyLichHen")]
	public partial class linqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_giaovien(tb_giaovien instance);
    partial void Updatetb_giaovien(tb_giaovien instance);
    partial void Deletetb_giaovien(tb_giaovien instance);
    partial void Inserttb_user(tb_user instance);
    partial void Updatetb_user(tb_user instance);
    partial void Deletetb_user(tb_user instance);
    partial void Inserttb_sinhvien(tb_sinhvien instance);
    partial void Updatetb_sinhvien(tb_sinhvien instance);
    partial void Deletetb_sinhvien(tb_sinhvien instance);
    partial void Inserttb_lichhen(tb_lichhen instance);
    partial void Updatetb_lichhen(tb_lichhen instance);
    partial void Deletetb_lichhen(tb_lichhen instance);
    partial void Inserttb_lichnghi(tb_lichnghi instance);
    partial void Updatetb_lichnghi(tb_lichnghi instance);
    partial void Deletetb_lichnghi(tb_lichnghi instance);
    #endregion
		
		public linqDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DangKyLichHenConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_giaovien> tb_giaoviens
		{
			get
			{
				return this.GetTable<tb_giaovien>();
			}
		}
		
		public System.Data.Linq.Table<tb_user> tb_users
		{
			get
			{
				return this.GetTable<tb_user>();
			}
		}
		
		public System.Data.Linq.Table<tb_sinhvien> tb_sinhviens
		{
			get
			{
				return this.GetTable<tb_sinhvien>();
			}
		}
		
		public System.Data.Linq.Table<tb_lichhen> tb_lichhens
		{
			get
			{
				return this.GetTable<tb_lichhen>();
			}
		}
		
		public System.Data.Linq.Table<tb_lichnghi> tb_lichnghis
		{
			get
			{
				return this.GetTable<tb_lichnghi>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GiaoVien_load_list")]
		public ISingleResult<GiaoVien_load_listResult> GiaoVien_load_list()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GiaoVien_load_listResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SinhVien_update")]
		public ISingleResult<SinhVien_updateResult> SinhVien_update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ma_sv", DbType="NVarChar(50)")] string ma_sv, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ten_sv", DbType="NVarChar(100)")] string ten_sv, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CMND", DbType="NVarChar(50)")] string cMND, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sđt, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ngay_sinh", DbType="DateTime")] System.Nullable<System.DateTime> ngay_sinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gioi_tinh", DbType="NVarChar(50)")] string gioi_tinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Active", DbType="Int")] System.Nullable<int> active, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PassWord", DbType="NVarChar(50)")] string passWord)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, ma_sv, ten_sv, cMND, sđt, email, ngay_sinh, gioi_tinh, active, userName, passWord);
			return ((ISingleResult<SinhVien_updateResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SinhVien_delete")]
		public int SinhVien_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SinhVien_insert")]
		public ISingleResult<SinhVien_insertResult> SinhVien_insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ma_sv", DbType="NVarChar(50)")] string ma_sv, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ten_sv", DbType="NVarChar(100)")] string ten_sv, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CMND", DbType="NVarChar(50)")] string cMND, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sđt, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ngay_sinh", DbType="DateTime")] System.Nullable<System.DateTime> ngay_sinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gioi_tinh", DbType="NVarChar(50)")] string gioi_tinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Active", DbType="Int")] System.Nullable<int> active, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PassWord", DbType="NVarChar(50)")] string passWord)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma_sv, ten_sv, cMND, sđt, email, ngay_sinh, gioi_tinh, active, userName, passWord);
			return ((ISingleResult<SinhVien_insertResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SinhVien_load_list")]
		public ISingleResult<SinhVien_load_listResult> SinhVien_load_list()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SinhVien_load_listResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GiaoVien_delete")]
		public int GiaoVien_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GiaoVien_update")]
		public ISingleResult<GiaoVien_updateResult> GiaoVien_update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ma_gv", DbType="NVarChar(50)")] string ma_gv, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ten_gv", DbType="NVarChar(100)")] string ten_gv, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gioi_tinh", DbType="NVarChar(50)")] string gioi_tinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ngay_sinh", DbType="DateTime")] System.Nullable<System.DateTime> ngay_sinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sđt", DbType="NVarChar(50)")] string sđt, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Active", DbType="Int")] System.Nullable<int> active, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PassWord", DbType="NVarChar(50)")] string passWord)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, ma_gv, ten_gv, gioi_tinh, ngay_sinh, email, sđt, active, userName, passWord);
			return ((ISingleResult<GiaoVien_updateResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GiaoVien_insert")]
		public ISingleResult<GiaoVien_insertResult> GiaoVien_insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ma_gv", DbType="NVarChar(50)")] string ma_gv, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ten_gv", DbType="NVarChar(100)")] string ten_gv, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gioi_tinh", DbType="NVarChar(50)")] string gioi_tinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ngay_sinh", DbType="DateTime")] System.Nullable<System.DateTime> ngay_sinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sđt", DbType="NVarChar(50)")] string sđt, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Active", DbType="Int")] System.Nullable<int> active, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PassWord", DbType="NVarChar(50)")] string passWord)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma_gv, ten_gv, gioi_tinh, ngay_sinh, email, sđt, active, userName, passWord);
			return ((ISingleResult<GiaoVien_insertResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GiaoVien_load_list")]
		public ISingleResult<GiaoVien_load_listResult1> GiaoVien_load_list1()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GiaoVien_load_listResult1>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LichHen_insert")]
		public ISingleResult<LichHen_insertResult> LichHen_insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ma_lich_hen", DbType="NVarChar(50)")] string ma_lich_hen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Noi_dung_hen", DbType="NVarChar(2000)")] string noi_dung_hen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_sv", DbType="NVarChar(50)")] string iD_sv, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_gv", DbType="NVarChar(10)")] string iD_gv, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ngay_hen", DbType="DateTime")] System.Nullable<System.DateTime> ngay_hen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gio_hen", DbType="Int")] System.Nullable<int> gio_hen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Active", DbType="Int")] System.Nullable<int> active, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ly_do_huy", DbType="NVarChar(2000)")] string ly_do_huy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreateUser", DbType="NVarChar(100)")] string createUser)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma_lich_hen, noi_dung_hen, iD_sv, iD_gv, ngay_hen, gio_hen, active, ly_do_huy, createUser);
			return ((ISingleResult<LichHen_insertResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LichHen_load_list")]
		public ISingleResult<LichHen_load_listResult> LichHen_load_list()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<LichHen_load_listResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LichHen_update")]
		public ISingleResult<LichHen_updateResult> LichHen_update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Active", DbType="Int")] System.Nullable<int> active, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lydohuy", DbType="NVarChar(2000)")] string lydohuy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModifyUser", DbType="NVarChar(50)")] string modifyUser)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, active, lydohuy, modifyUser);
			return ((ISingleResult<LichHen_updateResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChangePassword")]
		public ISingleResult<ChangePasswordResult> ChangePassword([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(400)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PasswordOld", DbType="NVarChar(50)")] string passwordOld, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PasswordNew", DbType="NVarChar(50)")] string passwordNew)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, passwordOld, passwordNew);
			return ((ISingleResult<ChangePasswordResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChangePasswordGV")]
		public ISingleResult<ChangePasswordGVResult> ChangePasswordGV([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(400)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PasswordOld", DbType="NVarChar(50)")] string passwordOld, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PasswordNew", DbType="NVarChar(50)")] string passwordNew)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, passwordOld, passwordNew);
			return ((ISingleResult<ChangePasswordGVResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChangePasswordSV")]
		public ISingleResult<ChangePasswordSVResult> ChangePasswordSV([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(400)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PasswordOld", DbType="NVarChar(50)")] string passwordOld, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PasswordNew", DbType="NVarChar(50)")] string passwordNew)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, passwordOld, passwordNew);
			return ((ISingleResult<ChangePasswordSVResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GiaoVien_load_lichnghi")]
		public ISingleResult<GiaoVien_load_lichnghiResult> GiaoVien_load_lichnghi([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<GiaoVien_load_lichnghiResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LichNghi_insert")]
		public ISingleResult<LichNghi_insertResult> LichNghi_insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="NVarChar(50)")] string iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayNghi", DbType="DateTime")] System.Nullable<System.DateTime> ngayNghi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, ngayNghi);
			return ((ISingleResult<LichNghi_insertResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LichNghi_delete")]
		public int LichNghi_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="NVarChar(50)")] string iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GiaoVien_update_tt")]
		public ISingleResult<GiaoVien_update_ttResult> GiaoVien_update_tt([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ma_gv", DbType="NVarChar(50)")] string ma_gv, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ten_gv", DbType="NVarChar(100)")] string ten_gv, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gioi_tinh", DbType="NVarChar(50)")] string gioi_tinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ngay_sinh", DbType="DateTime")] System.Nullable<System.DateTime> ngay_sinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sđt", DbType="NVarChar(50)")] string sđt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, ma_gv, ten_gv, gioi_tinh, ngay_sinh, email, sđt);
			return ((ISingleResult<GiaoVien_update_ttResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_giaovien")]
	public partial class tb_giaovien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ma_gv;
		
		private string _Ten_gv;
		
		private string _Gioi_tinh;
		
		private System.Nullable<System.DateTime> _Ngay_sinh;
		
		private string _Email;
		
		private string _Sđt;
		
		private int _Active;
		
		private string _UserName;
		
		private string _PassWord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMa_gvChanging(string value);
    partial void OnMa_gvChanged();
    partial void OnTen_gvChanging(string value);
    partial void OnTen_gvChanged();
    partial void OnGioi_tinhChanging(string value);
    partial void OnGioi_tinhChanged();
    partial void OnNgay_sinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_sinhChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSđtChanging(string value);
    partial void OnSđtChanged();
    partial void OnActiveChanging(int value);
    partial void OnActiveChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPassWordChanging(string value);
    partial void OnPassWordChanged();
    #endregion
		
		public tb_giaovien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_gv", DbType="NVarChar(50)")]
		public string Ma_gv
		{
			get
			{
				return this._Ma_gv;
			}
			set
			{
				if ((this._Ma_gv != value))
				{
					this.OnMa_gvChanging(value);
					this.SendPropertyChanging();
					this._Ma_gv = value;
					this.SendPropertyChanged("Ma_gv");
					this.OnMa_gvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_gv", DbType="NVarChar(100)")]
		public string Ten_gv
		{
			get
			{
				return this._Ten_gv;
			}
			set
			{
				if ((this._Ten_gv != value))
				{
					this.OnTen_gvChanging(value);
					this.SendPropertyChanging();
					this._Ten_gv = value;
					this.SendPropertyChanged("Ten_gv");
					this.OnTen_gvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioi_tinh", DbType="NVarChar(50)")]
		public string Gioi_tinh
		{
			get
			{
				return this._Gioi_tinh;
			}
			set
			{
				if ((this._Gioi_tinh != value))
				{
					this.OnGioi_tinhChanging(value);
					this.SendPropertyChanging();
					this._Gioi_tinh = value;
					this.SendPropertyChanged("Gioi_tinh");
					this.OnGioi_tinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_sinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay_sinh
		{
			get
			{
				return this._Ngay_sinh;
			}
			set
			{
				if ((this._Ngay_sinh != value))
				{
					this.OnNgay_sinhChanging(value);
					this.SendPropertyChanging();
					this._Ngay_sinh = value;
					this.SendPropertyChanged("Ngay_sinh");
					this.OnNgay_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sđt", DbType="NVarChar(50)")]
		public string Sđt
		{
			get
			{
				return this._Sđt;
			}
			set
			{
				if ((this._Sđt != value))
				{
					this.OnSđtChanging(value);
					this.SendPropertyChanging();
					this._Sđt = value;
					this.SendPropertyChanged("Sđt");
					this.OnSđtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Int NOT NULL")]
		public int Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(200)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="NVarChar(200)")]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this.OnPassWordChanging(value);
					this.SendPropertyChanging();
					this._PassWord = value;
					this.SendPropertyChanged("PassWord");
					this.OnPassWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_user")]
	public partial class tb_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _UserName;
		
		private string _PassWord;
		
		private string _FullName;
		
		private string _Email;
		
		private string _Sđt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPassWordChanging(string value);
    partial void OnPassWordChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSđtChanging(string value);
    partial void OnSđtChanged();
    #endregion
		
		public tb_user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="NVarChar(50)")]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this.OnPassWordChanging(value);
					this.SendPropertyChanging();
					this._PassWord = value;
					this.SendPropertyChanged("PassWord");
					this.OnPassWordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(200)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sđt", DbType="NVarChar(50)")]
		public string Sđt
		{
			get
			{
				return this._Sđt;
			}
			set
			{
				if ((this._Sđt != value))
				{
					this.OnSđtChanging(value);
					this.SendPropertyChanging();
					this._Sđt = value;
					this.SendPropertyChanged("Sđt");
					this.OnSđtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_sinhvien")]
	public partial class tb_sinhvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ma_sv;
		
		private string _Ten_sv;
		
		private string _CMND;
		
		private string _Sđt;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _Ngay_sinh;
		
		private string _Gioi_tinh;
		
		private int _Active;
		
		private string _UserName;
		
		private string _PassWord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMa_svChanging(string value);
    partial void OnMa_svChanged();
    partial void OnTen_svChanging(string value);
    partial void OnTen_svChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnSđtChanging(string value);
    partial void OnSđtChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNgay_sinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_sinhChanged();
    partial void OnGioi_tinhChanging(string value);
    partial void OnGioi_tinhChanged();
    partial void OnActiveChanging(int value);
    partial void OnActiveChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPassWordChanging(string value);
    partial void OnPassWordChanged();
    #endregion
		
		public tb_sinhvien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_sv", DbType="NVarChar(50)")]
		public string Ma_sv
		{
			get
			{
				return this._Ma_sv;
			}
			set
			{
				if ((this._Ma_sv != value))
				{
					this.OnMa_svChanging(value);
					this.SendPropertyChanging();
					this._Ma_sv = value;
					this.SendPropertyChanged("Ma_sv");
					this.OnMa_svChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_sv", DbType="NVarChar(100)")]
		public string Ten_sv
		{
			get
			{
				return this._Ten_sv;
			}
			set
			{
				if ((this._Ten_sv != value))
				{
					this.OnTen_svChanging(value);
					this.SendPropertyChanging();
					this._Ten_sv = value;
					this.SendPropertyChanged("Ten_sv");
					this.OnTen_svChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(50)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sđt", DbType="NVarChar(50)")]
		public string Sđt
		{
			get
			{
				return this._Sđt;
			}
			set
			{
				if ((this._Sđt != value))
				{
					this.OnSđtChanging(value);
					this.SendPropertyChanging();
					this._Sđt = value;
					this.SendPropertyChanged("Sđt");
					this.OnSđtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_sinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay_sinh
		{
			get
			{
				return this._Ngay_sinh;
			}
			set
			{
				if ((this._Ngay_sinh != value))
				{
					this.OnNgay_sinhChanging(value);
					this.SendPropertyChanging();
					this._Ngay_sinh = value;
					this.SendPropertyChanged("Ngay_sinh");
					this.OnNgay_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioi_tinh", DbType="NVarChar(50)")]
		public string Gioi_tinh
		{
			get
			{
				return this._Gioi_tinh;
			}
			set
			{
				if ((this._Gioi_tinh != value))
				{
					this.OnGioi_tinhChanging(value);
					this.SendPropertyChanging();
					this._Gioi_tinh = value;
					this.SendPropertyChanged("Gioi_tinh");
					this.OnGioi_tinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Int NOT NULL")]
		public int Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="NVarChar(50)")]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this.OnPassWordChanging(value);
					this.SendPropertyChanging();
					this._PassWord = value;
					this.SendPropertyChanged("PassWord");
					this.OnPassWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_lichhen")]
	public partial class tb_lichhen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_lich_hen;
		
		private string _Ma_lich_hen;
		
		private string _Noi_dung_hen;
		
		private string _ID_sv;
		
		private string _ID_gv;
		
		private System.Nullable<System.DateTime> _Ngay_hen;
		
		private System.Nullable<int> _Gio_hen;
		
		private int _Active;
		
		private string _Ly_do_huy;
		
		private string _CreateUser;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _ModifyUser;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_lich_henChanging(int value);
    partial void OnID_lich_henChanged();
    partial void OnMa_lich_henChanging(string value);
    partial void OnMa_lich_henChanged();
    partial void OnNoi_dung_henChanging(string value);
    partial void OnNoi_dung_henChanged();
    partial void OnID_svChanging(string value);
    partial void OnID_svChanged();
    partial void OnID_gvChanging(string value);
    partial void OnID_gvChanged();
    partial void OnNgay_henChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_henChanged();
    partial void OnGio_henChanging(System.Nullable<int> value);
    partial void OnGio_henChanged();
    partial void OnActiveChanging(int value);
    partial void OnActiveChanged();
    partial void OnLy_do_huyChanging(string value);
    partial void OnLy_do_huyChanged();
    partial void OnCreateUserChanging(string value);
    partial void OnCreateUserChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnModifyUserChanging(string value);
    partial void OnModifyUserChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    #endregion
		
		public tb_lichhen()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_lich_hen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_lich_hen
		{
			get
			{
				return this._ID_lich_hen;
			}
			set
			{
				if ((this._ID_lich_hen != value))
				{
					this.OnID_lich_henChanging(value);
					this.SendPropertyChanging();
					this._ID_lich_hen = value;
					this.SendPropertyChanged("ID_lich_hen");
					this.OnID_lich_henChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_lich_hen", DbType="NVarChar(50)")]
		public string Ma_lich_hen
		{
			get
			{
				return this._Ma_lich_hen;
			}
			set
			{
				if ((this._Ma_lich_hen != value))
				{
					this.OnMa_lich_henChanging(value);
					this.SendPropertyChanging();
					this._Ma_lich_hen = value;
					this.SendPropertyChanged("Ma_lich_hen");
					this.OnMa_lich_henChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noi_dung_hen", DbType="NVarChar(2000)")]
		public string Noi_dung_hen
		{
			get
			{
				return this._Noi_dung_hen;
			}
			set
			{
				if ((this._Noi_dung_hen != value))
				{
					this.OnNoi_dung_henChanging(value);
					this.SendPropertyChanging();
					this._Noi_dung_hen = value;
					this.SendPropertyChanged("Noi_dung_hen");
					this.OnNoi_dung_henChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_sv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ID_sv
		{
			get
			{
				return this._ID_sv;
			}
			set
			{
				if ((this._ID_sv != value))
				{
					this.OnID_svChanging(value);
					this.SendPropertyChanging();
					this._ID_sv = value;
					this.SendPropertyChanged("ID_sv");
					this.OnID_svChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_gv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ID_gv
		{
			get
			{
				return this._ID_gv;
			}
			set
			{
				if ((this._ID_gv != value))
				{
					this.OnID_gvChanging(value);
					this.SendPropertyChanging();
					this._ID_gv = value;
					this.SendPropertyChanged("ID_gv");
					this.OnID_gvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_hen", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay_hen
		{
			get
			{
				return this._Ngay_hen;
			}
			set
			{
				if ((this._Ngay_hen != value))
				{
					this.OnNgay_henChanging(value);
					this.SendPropertyChanging();
					this._Ngay_hen = value;
					this.SendPropertyChanged("Ngay_hen");
					this.OnNgay_henChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gio_hen", DbType="Int")]
		public System.Nullable<int> Gio_hen
		{
			get
			{
				return this._Gio_hen;
			}
			set
			{
				if ((this._Gio_hen != value))
				{
					this.OnGio_henChanging(value);
					this.SendPropertyChanging();
					this._Gio_hen = value;
					this.SendPropertyChanged("Gio_hen");
					this.OnGio_henChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Int NOT NULL")]
		public int Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ly_do_huy", DbType="NVarChar(200)")]
		public string Ly_do_huy
		{
			get
			{
				return this._Ly_do_huy;
			}
			set
			{
				if ((this._Ly_do_huy != value))
				{
					this.OnLy_do_huyChanging(value);
					this.SendPropertyChanging();
					this._Ly_do_huy = value;
					this.SendPropertyChanged("Ly_do_huy");
					this.OnLy_do_huyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="NVarChar(50)")]
		public string CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this.OnCreateUserChanging(value);
					this.SendPropertyChanging();
					this._CreateUser = value;
					this.SendPropertyChanged("CreateUser");
					this.OnCreateUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyUser", DbType="NVarChar(50)")]
		public string ModifyUser
		{
			get
			{
				return this._ModifyUser;
			}
			set
			{
				if ((this._ModifyUser != value))
				{
					this.OnModifyUserChanging(value);
					this.SendPropertyChanging();
					this._ModifyUser = value;
					this.SendPropertyChanged("ModifyUser");
					this.OnModifyUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_lichnghi")]
	public partial class tb_lichnghi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDChiTiet;
		
		private System.Nullable<int> _ID_gv;
		
		private System.Nullable<System.DateTime> _Ngay_nghi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChiTietChanging(int value);
    partial void OnIDChiTietChanged();
    partial void OnID_gvChanging(System.Nullable<int> value);
    partial void OnID_gvChanged();
    partial void OnNgay_nghiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_nghiChanged();
    #endregion
		
		public tb_lichnghi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChiTiet", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDChiTiet
		{
			get
			{
				return this._IDChiTiet;
			}
			set
			{
				if ((this._IDChiTiet != value))
				{
					this.OnIDChiTietChanging(value);
					this.SendPropertyChanging();
					this._IDChiTiet = value;
					this.SendPropertyChanged("IDChiTiet");
					this.OnIDChiTietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_gv", DbType="Int")]
		public System.Nullable<int> ID_gv
		{
			get
			{
				return this._ID_gv;
			}
			set
			{
				if ((this._ID_gv != value))
				{
					this.OnID_gvChanging(value);
					this.SendPropertyChanging();
					this._ID_gv = value;
					this.SendPropertyChanged("ID_gv");
					this.OnID_gvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_nghi", DbType="Date")]
		public System.Nullable<System.DateTime> Ngay_nghi
		{
			get
			{
				return this._Ngay_nghi;
			}
			set
			{
				if ((this._Ngay_nghi != value))
				{
					this.OnNgay_nghiChanging(value);
					this.SendPropertyChanging();
					this._Ngay_nghi = value;
					this.SendPropertyChanged("Ngay_nghi");
					this.OnNgay_nghiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GiaoVien_load_listResult
	{
		
		private int _ID;
		
		private string _Ma_gv;
		
		private string _Ten_gv;
		
		private string _Gioi_tinh;
		
		private System.Nullable<System.DateTime> _Ngay_sinh;
		
		private string _Email;
		
		private string _Sđt;
		
		private int _Active;
		
		private string _UserName;
		
		private string _PassWord;
		
		public GiaoVien_load_listResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_gv", DbType="NVarChar(50)")]
		public string Ma_gv
		{
			get
			{
				return this._Ma_gv;
			}
			set
			{
				if ((this._Ma_gv != value))
				{
					this._Ma_gv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_gv", DbType="NVarChar(100)")]
		public string Ten_gv
		{
			get
			{
				return this._Ten_gv;
			}
			set
			{
				if ((this._Ten_gv != value))
				{
					this._Ten_gv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioi_tinh", DbType="NVarChar(50)")]
		public string Gioi_tinh
		{
			get
			{
				return this._Gioi_tinh;
			}
			set
			{
				if ((this._Gioi_tinh != value))
				{
					this._Gioi_tinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_sinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay_sinh
		{
			get
			{
				return this._Ngay_sinh;
			}
			set
			{
				if ((this._Ngay_sinh != value))
				{
					this._Ngay_sinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sđt", DbType="NVarChar(50)")]
		public string Sđt
		{
			get
			{
				return this._Sđt;
			}
			set
			{
				if ((this._Sđt != value))
				{
					this._Sđt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Int NOT NULL")]
		public int Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(200)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="NVarChar(200)")]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this._PassWord = value;
				}
			}
		}
	}
	
	public partial class SinhVien_updateResult
	{
		
		private int _Updated;
		
		public SinhVien_updateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="Int NOT NULL")]
		public int Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this._Updated = value;
				}
			}
		}
	}
	
	public partial class SinhVien_insertResult
	{
		
		private int _Identity;
		
		public SinhVien_insertResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Identity]", Storage="_Identity", DbType="Int NOT NULL")]
		public int Identity
		{
			get
			{
				return this._Identity;
			}
			set
			{
				if ((this._Identity != value))
				{
					this._Identity = value;
				}
			}
		}
	}
	
	public partial class SinhVien_load_listResult
	{
		
		private int _ID;
		
		private string _Ma_sv;
		
		private string _Ten_sv;
		
		private string _CMND;
		
		private string _Sđt;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _Ngay_sinh;
		
		private string _Gioi_tinh;
		
		private int _Active;
		
		private string _UserName;
		
		private string _PassWord;
		
		public SinhVien_load_listResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_sv", DbType="NVarChar(50)")]
		public string Ma_sv
		{
			get
			{
				return this._Ma_sv;
			}
			set
			{
				if ((this._Ma_sv != value))
				{
					this._Ma_sv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_sv", DbType="NVarChar(100)")]
		public string Ten_sv
		{
			get
			{
				return this._Ten_sv;
			}
			set
			{
				if ((this._Ten_sv != value))
				{
					this._Ten_sv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(50)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this._CMND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sđt", DbType="NVarChar(50)")]
		public string Sđt
		{
			get
			{
				return this._Sđt;
			}
			set
			{
				if ((this._Sđt != value))
				{
					this._Sđt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_sinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay_sinh
		{
			get
			{
				return this._Ngay_sinh;
			}
			set
			{
				if ((this._Ngay_sinh != value))
				{
					this._Ngay_sinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioi_tinh", DbType="NVarChar(50)")]
		public string Gioi_tinh
		{
			get
			{
				return this._Gioi_tinh;
			}
			set
			{
				if ((this._Gioi_tinh != value))
				{
					this._Gioi_tinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Int NOT NULL")]
		public int Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="NVarChar(50)")]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this._PassWord = value;
				}
			}
		}
	}
	
	public partial class GiaoVien_updateResult
	{
		
		private int _Updated;
		
		public GiaoVien_updateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="Int NOT NULL")]
		public int Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this._Updated = value;
				}
			}
		}
	}
	
	public partial class GiaoVien_insertResult
	{
		
		private int _Identity;
		
		public GiaoVien_insertResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Identity]", Storage="_Identity", DbType="Int NOT NULL")]
		public int Identity
		{
			get
			{
				return this._Identity;
			}
			set
			{
				if ((this._Identity != value))
				{
					this._Identity = value;
				}
			}
		}
	}
	
	public partial class GiaoVien_load_listResult1
	{
		
		private int _ID;
		
		private string _Ma_gv;
		
		private string _Ten_gv;
		
		private string _Gioi_tinh;
		
		private System.Nullable<System.DateTime> _Ngay_sinh;
		
		private string _Email;
		
		private string _Sđt;
		
		private int _Active;
		
		private string _UserName;
		
		private string _PassWord;
		
		public GiaoVien_load_listResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_gv", DbType="NVarChar(50)")]
		public string Ma_gv
		{
			get
			{
				return this._Ma_gv;
			}
			set
			{
				if ((this._Ma_gv != value))
				{
					this._Ma_gv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_gv", DbType="NVarChar(100)")]
		public string Ten_gv
		{
			get
			{
				return this._Ten_gv;
			}
			set
			{
				if ((this._Ten_gv != value))
				{
					this._Ten_gv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioi_tinh", DbType="NVarChar(50)")]
		public string Gioi_tinh
		{
			get
			{
				return this._Gioi_tinh;
			}
			set
			{
				if ((this._Gioi_tinh != value))
				{
					this._Gioi_tinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_sinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay_sinh
		{
			get
			{
				return this._Ngay_sinh;
			}
			set
			{
				if ((this._Ngay_sinh != value))
				{
					this._Ngay_sinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sđt", DbType="NVarChar(50)")]
		public string Sđt
		{
			get
			{
				return this._Sđt;
			}
			set
			{
				if ((this._Sđt != value))
				{
					this._Sđt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Int NOT NULL")]
		public int Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(200)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="NVarChar(200)")]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this._PassWord = value;
				}
			}
		}
	}
	
	public partial class LichHen_insertResult
	{
		
		private int _Identity;
		
		public LichHen_insertResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Identity]", Storage="_Identity", DbType="Int NOT NULL")]
		public int Identity
		{
			get
			{
				return this._Identity;
			}
			set
			{
				if ((this._Identity != value))
				{
					this._Identity = value;
				}
			}
		}
	}
	
	public partial class LichHen_load_listResult
	{
		
		private int _ID_lich_hen;
		
		private string _Ma_lich_hen;
		
		private string _Noi_dung_hen;
		
		private string _ID_sv;
		
		private string _ID_gv;
		
		private System.Nullable<System.DateTime> _Ngay_hen;
		
		private System.Nullable<int> _Gio_hen;
		
		private int _Active;
		
		private string _Ly_do_huy;
		
		private string _CreateUser;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _ModifyUser;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private string _Ten_sv;
		
		private string _Ten_gv;
		
		public LichHen_load_listResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_lich_hen", DbType="Int NOT NULL")]
		public int ID_lich_hen
		{
			get
			{
				return this._ID_lich_hen;
			}
			set
			{
				if ((this._ID_lich_hen != value))
				{
					this._ID_lich_hen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_lich_hen", DbType="NVarChar(50)")]
		public string Ma_lich_hen
		{
			get
			{
				return this._Ma_lich_hen;
			}
			set
			{
				if ((this._Ma_lich_hen != value))
				{
					this._Ma_lich_hen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noi_dung_hen", DbType="NVarChar(2000)")]
		public string Noi_dung_hen
		{
			get
			{
				return this._Noi_dung_hen;
			}
			set
			{
				if ((this._Noi_dung_hen != value))
				{
					this._Noi_dung_hen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_sv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ID_sv
		{
			get
			{
				return this._ID_sv;
			}
			set
			{
				if ((this._ID_sv != value))
				{
					this._ID_sv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_gv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ID_gv
		{
			get
			{
				return this._ID_gv;
			}
			set
			{
				if ((this._ID_gv != value))
				{
					this._ID_gv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_hen", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay_hen
		{
			get
			{
				return this._Ngay_hen;
			}
			set
			{
				if ((this._Ngay_hen != value))
				{
					this._Ngay_hen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gio_hen", DbType="Int")]
		public System.Nullable<int> Gio_hen
		{
			get
			{
				return this._Gio_hen;
			}
			set
			{
				if ((this._Gio_hen != value))
				{
					this._Gio_hen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Int NOT NULL")]
		public int Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ly_do_huy", DbType="NVarChar(200)")]
		public string Ly_do_huy
		{
			get
			{
				return this._Ly_do_huy;
			}
			set
			{
				if ((this._Ly_do_huy != value))
				{
					this._Ly_do_huy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="NVarChar(50)")]
		public string CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this._CreateUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyUser", DbType="NVarChar(50)")]
		public string ModifyUser
		{
			get
			{
				return this._ModifyUser;
			}
			set
			{
				if ((this._ModifyUser != value))
				{
					this._ModifyUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_sv", DbType="NVarChar(100)")]
		public string Ten_sv
		{
			get
			{
				return this._Ten_sv;
			}
			set
			{
				if ((this._Ten_sv != value))
				{
					this._Ten_sv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_gv", DbType="NVarChar(100)")]
		public string Ten_gv
		{
			get
			{
				return this._Ten_gv;
			}
			set
			{
				if ((this._Ten_gv != value))
				{
					this._Ten_gv = value;
				}
			}
		}
	}
	
	public partial class LichHen_updateResult
	{
		
		private int _Updated;
		
		public LichHen_updateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="Int NOT NULL")]
		public int Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this._Updated = value;
				}
			}
		}
	}
	
	public partial class ChangePasswordResult
	{
		
		private int _Updated;
		
		public ChangePasswordResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="Int NOT NULL")]
		public int Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this._Updated = value;
				}
			}
		}
	}
	
	public partial class ChangePasswordGVResult
	{
		
		private int _Updated;
		
		public ChangePasswordGVResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="Int NOT NULL")]
		public int Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this._Updated = value;
				}
			}
		}
	}
	
	public partial class ChangePasswordSVResult
	{
		
		private int _Updated;
		
		public ChangePasswordSVResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="Int NOT NULL")]
		public int Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this._Updated = value;
				}
			}
		}
	}
	
	public partial class GiaoVien_load_lichnghiResult
	{
		
		private int _IDChiTiet;
		
		private System.Nullable<int> _ID_gv;
		
		private System.Nullable<System.DateTime> _Ngay_nghi;
		
		public GiaoVien_load_lichnghiResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChiTiet", DbType="Int NOT NULL")]
		public int IDChiTiet
		{
			get
			{
				return this._IDChiTiet;
			}
			set
			{
				if ((this._IDChiTiet != value))
				{
					this._IDChiTiet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_gv", DbType="Int")]
		public System.Nullable<int> ID_gv
		{
			get
			{
				return this._ID_gv;
			}
			set
			{
				if ((this._ID_gv != value))
				{
					this._ID_gv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_nghi", DbType="Date")]
		public System.Nullable<System.DateTime> Ngay_nghi
		{
			get
			{
				return this._Ngay_nghi;
			}
			set
			{
				if ((this._Ngay_nghi != value))
				{
					this._Ngay_nghi = value;
				}
			}
		}
	}
	
	public partial class LichNghi_insertResult
	{
		
		private int _Identity;
		
		public LichNghi_insertResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Identity]", Storage="_Identity", DbType="Int NOT NULL")]
		public int Identity
		{
			get
			{
				return this._Identity;
			}
			set
			{
				if ((this._Identity != value))
				{
					this._Identity = value;
				}
			}
		}
	}
	
	public partial class GiaoVien_update_ttResult
	{
		
		private int _Updated;
		
		public GiaoVien_update_ttResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="Int NOT NULL")]
		public int Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this._Updated = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
