<?xml version="1.0" encoding="utf-8"?><Database Name="DangKyLichHen" Class="linqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-NA1SDU2\NHATANH;Initial Catalog=DangKyLichHen;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DangKyLichHenConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_giaovien" Member="tb_giaoviens">
    <Type Name="tb_giaovien">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ma_gv" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ten_gv" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Gioi_tinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngay_sinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Sđt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PassWord" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_user" Member="tb_users">
    <Type Name="tb_user">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PassWord" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Sđt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_sinhvien" Member="tb_sinhviens">
    <Type Name="tb_sinhvien">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ma_sv" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ten_sv" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sđt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Ngay_sinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Gioi_tinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PassWord" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_lichhen" Member="tb_lichhens">
    <Type Name="tb_lichhen">
      <Column Name="ID_lich_hen" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ma_lich_hen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Noi_dung_hen" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="ID_sv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_gv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ngay_hen" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Gio_hen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ly_do_huy" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_lichnghi" Member="tb_lichnghis">
    <Type Name="tb_lichnghi">
      <Column Name="IDChiTiet" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_gv" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ngay_nghi" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GiaoVien_load_list" Method="GiaoVien_load_list">
    <ElementType Name="GiaoVien_load_listResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ma_gv" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ten_gv" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Gioi_tinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngay_sinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Sđt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PassWord" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SinhVien_update" Method="SinhVien_update">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ma_sv" Parameter="ma_sv" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ten_sv" Parameter="ten_sv" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="CMND" Parameter="cMND" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="sđt" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ngay_sinh" Parameter="ngay_sinh" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Gioi_tinh" Parameter="gioi_tinh" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Active" Parameter="active" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PassWord" Parameter="passWord" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="SinhVien_updateResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SinhVien_delete" Method="SinhVien_delete">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SinhVien_insert" Method="SinhVien_insert">
    <Parameter Name="Ma_sv" Parameter="ma_sv" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ten_sv" Parameter="ten_sv" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="CMND" Parameter="cMND" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="sđt" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ngay_sinh" Parameter="ngay_sinh" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Gioi_tinh" Parameter="gioi_tinh" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Active" Parameter="active" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PassWord" Parameter="passWord" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="SinhVien_insertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SinhVien_load_list" Method="SinhVien_load_list">
    <ElementType Name="SinhVien_load_listResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ma_sv" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ten_sv" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sđt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Ngay_sinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Gioi_tinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PassWord" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GiaoVien_delete" Method="GiaoVien_delete">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GiaoVien_update" Method="GiaoVien_update">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ma_gv" Parameter="ma_gv" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ten_gv" Parameter="ten_gv" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Gioi_tinh" Parameter="gioi_tinh" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ngay_sinh" Parameter="ngay_sinh" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Sđt" Parameter="sđt" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Active" Parameter="active" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PassWord" Parameter="passWord" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GiaoVien_updateResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GiaoVien_insert" Method="GiaoVien_insert">
    <Parameter Name="Ma_gv" Parameter="ma_gv" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ten_gv" Parameter="ten_gv" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Gioi_tinh" Parameter="gioi_tinh" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ngay_sinh" Parameter="ngay_sinh" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Sđt" Parameter="sđt" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Active" Parameter="active" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PassWord" Parameter="passWord" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GiaoVien_insertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GiaoVien_load_list" Method="GiaoVien_load_list1">
    <ElementType Name="GiaoVien_load_listResult1">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ma_gv" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ten_gv" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Gioi_tinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngay_sinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Sđt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PassWord" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LichHen_insert" Method="LichHen_insert">
    <Parameter Name="Ma_lich_hen" Parameter="ma_lich_hen" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Noi_dung_hen" Parameter="noi_dung_hen" Type="System.String" DbType="NVarChar(2000)" />
    <Parameter Name="ID_sv" Parameter="iD_sv" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ID_gv" Parameter="iD_gv" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Ngay_hen" Parameter="ngay_hen" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Gio_hen" Parameter="gio_hen" Type="System.Int32" DbType="Int" />
    <Parameter Name="Active" Parameter="active" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ly_do_huy" Parameter="ly_do_huy" Type="System.String" DbType="NVarChar(2000)" />
    <Parameter Name="CreateUser" Parameter="createUser" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="LichHen_insertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.LichHen_load_list" Method="LichHen_load_list">
    <ElementType Name="LichHen_load_listResult">
      <Column Name="ID_lich_hen" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ma_lich_hen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Noi_dung_hen" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="ID_sv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_gv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ngay_hen" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Gio_hen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ly_do_huy" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ten_sv" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Ten_gv" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LichHen_update" Method="LichHen_update">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Active" Parameter="active" Type="System.Int32" DbType="Int" />
    <Parameter Name="Lydohuy" Parameter="lydohuy" Type="System.String" DbType="NVarChar(2000)" />
    <Parameter Name="ModifyUser" Parameter="modifyUser" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="LichHen_updateResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ChangePassword" Method="ChangePassword">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(400)" />
    <Parameter Name="PasswordOld" Parameter="passwordOld" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PasswordNew" Parameter="passwordNew" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="ChangePasswordResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ChangePasswordGV" Method="ChangePasswordGV">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(400)" />
    <Parameter Name="PasswordOld" Parameter="passwordOld" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PasswordNew" Parameter="passwordNew" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="ChangePasswordGVResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ChangePasswordSV" Method="ChangePasswordSV">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(400)" />
    <Parameter Name="PasswordOld" Parameter="passwordOld" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PasswordNew" Parameter="passwordNew" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="ChangePasswordSVResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GiaoVien_load_lichnghi" Method="GiaoVien_load_lichnghi">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="GiaoVien_load_lichnghiResult">
      <Column Name="IDChiTiet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_gv" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ngay_nghi" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LichNghi_insert" Method="LichNghi_insert">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="NgayNghi" Parameter="ngayNghi" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="LichNghi_insertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.LichNghi_delete" Method="LichNghi_delete">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GiaoVien_update_tt" Method="GiaoVien_update_tt">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ma_gv" Parameter="ma_gv" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ten_gv" Parameter="ten_gv" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Gioi_tinh" Parameter="gioi_tinh" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ngay_sinh" Parameter="ngay_sinh" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Sđt" Parameter="sđt" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GiaoVien_update_ttResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>